name: Publish image on ghcr.io

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                scheme: [verovio-humlib-docker-image]
        env:
            SCHEME: ${{ matrix.scheme }}
        steps:
            -
                uses: actions/checkout@v2
            -
                name: Build
                run: docker build -t $SCHEME -f Dockerfile .
            -
                name: Deploy
                run: |
                    TAG="ghcr.io/wolfgangdrescher/$SCHEME"
                    VERSION="$(date "+%Y%m%d")"
                    docker tag $SCHEME $TAG:$VERSION
                    docker tag $SCHEME $TAG:latest
                    docker images $TAG
                    echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
                    docker push $TAG:$VERSION
                    docker push $TAG:latest
